cancel -k and --foreign-keys options
"  -k           distribute each table by primary key\n"
"  --foreign-keys           create foreign key constraints between tables\n"
-----------------------------------------------------------------------------------------------------------
if create all test-tables distribute by branch id, pgxc can't create a primary key by itself 's id. because pgxc does not support that they are different columns between distribute key and primary key. if that, pgxc prompt a error like this:
LOG:  statement: alter table pgbench_tellers add primary key (tid)
ERROR:  Cannot create index whose evaluation cannot be enforced to remote nodes
since the -k and --foreign-keys options can not work in pgxc, it should not be open at present.