While generating remote column aliases, make use of user-supplied column aliases if available, and use the physical table attributes only if user has not supplied column aliases. The issue was: if a remote join query has user column aliases, they were not getting used in the quals of remote join query, and so the query used to give error such as:
SELECT '' AS "xxx", t1.a, t2.e
 FROM J1_TBL t1 (a, b, c), J2_TBL t2 (d, e)
  WHERE t1.a = t2.d
   ORDER BY a, e;
ERROR:  column in_1.i does not exist